name = "drive"
type = "webpack"
workers_dev = true
account_id = "d96b954c073f56241cbde82d59e51da8"
zone_id = "4d967ac4b1a4af58a1a746f78d51bac9"
kv_namespaces = [
    { binding = "BUCKET", id = "343981ccc8ef46c482f8ee6863163d81" }
]

[env.staging]
name = "drive-staging"
